# Generated by Django 5.0.1 on 2024-01-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_at', 'name'), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
