# Generated by Django 5.0.1 on 2024-01-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repository_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
